WIP: VASP
mit-orcd/orcd-docs-edit pull request #24
Opened 2023-10-11 02:54 UTC by christophernhill

2023-10-24 17:11 UTC, shaohao99 approved these changes

2023-10-30 17:36 UTC, lmilechin requested changes
Two things to address, it looks like we lost part of a sentence and it might be good to separate out a compile script and a run script.

2023-10-30 18:06 UTC, christophernhill commented on docs/recipes/basic_vasp_gcc_example.md
> +make -j OPENBLAS_ROOT=$OPENBLAS_ROOT FFTW_ROOT=$FFTW_ROOT SCALAPACK_ROOT=$SCALAPACK_ROOT MODS=1 DEPS=1
@lmilechin - the two steps are separate. I'll split. 

FYI - I am exploring having a section scripts that can be run at the end of some recipes with some reference output (where it makes sense). That could then be a way to do some automated checking whether a recipe is still fully functioning.

2023-10-30 20:16 UTC, lmilechin commented on docs/recipes/basic_vasp_gcc_example.md
> +make -j OPENBLAS_ROOT=$OPENBLAS_ROOT FFTW_ROOT=$FFTW_ROOT SCALAPACK_ROOT=$SCALAPACK_ROOT MODS=1 DEPS=1
Sounds good!

2023-10-31 20:00 UTC, lmilechin approved these changes
Sounds like there might be another change coming, but looks good up to this point.

2025-02-28 18:18 UTC, shaohao99 commented
I have checked that. It is good to go.

2025-02-28 19:23 UTC, merged