MPI jobs
mit-orcd/orcd-docs-edit pull request #38
Opened 2024-02-27 20:49 UTC by shaohao99

Add recipes for MPI jobs.

2024-02-27 20:56 UTC, shaohao99 commented
Preview
https://mit-orcd.github.io/orcd-docs-previews/PR/PR38/recipes/mpi/

2024-03-25 20:32 UTC, lmilechin requested changes

2024-03-25 20:32 UTC, lmilechin commented on docs/recipes/mpi.md
> +export OMP_NUMB_THREADS=$SLURM_CPUS_PER_TASK
Typo: OMP_NUMB_THREADS -> OMP_NUM_THREADS

2024-03-25 20:32 UTC, lmilechin commented on docs/recipes/mpi.md
> +export OMP_NUMB_THREADS=8
Typo: OMP_NUMB_THREADS -> OMP_NUM_THREADS

2024-03-25 20:32 UTC, lmilechin commented on docs/recipes/mpi.md
> + sinfo -N -p sched_mit_hill,newnodes,sched_any,sched_mit_orcd -o %f,%c,%m,%l,%t |grep -v drain
I suggest leaving out the -p flag, by default users will only see partitions they can submit jobs to, and adding %P to the output so users know which partition to select:
` sinfo -N -o %P,%f,%c,%m,%l,%t |grep -v drain`

2024-03-25 20:32 UTC, lmilechin commented on docs/recipes/relion.md
Did you intend to include RELION in this PR?

2024-03-26 16:53 UTC, shaohao99 commented on docs/recipes/relion.md
Yes, RELION is good to go too.

2024-03-27 14:34 UTC, lmilechin commented on docs/recipes/relion.md
Sounds good, I'll read through that one as well.

2024-03-27 14:47 UTC, lmilechin commented on docs/recipes/relion.md
> +> Note: The x86 nodes are available to some labs only.
Did you want to use the [admonition syntax](https://squidfunk.github.io/mkdocs-material/reference/admonitions/) for the Notes, as you did in the MPI pages? This one:

!!! Note
    The x86 nodes are available to some labs only.

2024-03-27 14:47 UTC, lmilechin commented on docs/recipes/relion.md
Looks good, just the one comment/suggestion about the notes.

2024-04-09 18:17 UTC, shaohao99 commented
I have modified both pages of MPI and RELION, and pushed it. I think it is good to go.

2024-04-29 15:06 UTC, shaohao99 commented
The MPI4py for EO is added to the page of MPI4py.

2024-04-29 15:07 UTC, merged