Adding Apptainer and Singularity
mit-orcd/orcd-docs-edit pull request #56
Opened 2024-05-20 22:13 UTC by shaohao99

This is to add Apptainer and Singularity.

2024-05-20 22:14 UTC, shaohao99 commented
Preview
https://mit-orcd.github.io/orcd-docs-previews/PR/PR56/software/apptainer/

2024-07-03 15:15 UTC, shaohao99 commented
@lmilechin  @christophernhill   I have completed this page for the container. The preview link is above.

2024-08-23 18:55 UTC, lmilechin requested changes
Overall good! There are a few typos to fix and some edits needed on the "Building" section.

2024-08-23 18:55 UTC, lmilechin commented on docs/software/apptainer.md
> +Container has great portability and mobility, that says, it is convenient to migrate your applications bewtween different platforms, such as laptops/desktops, cloud platforms and HPC clusters.
"Containers have"

2024-08-23 18:55 UTC, lmilechin commented on docs/software/apptainer.md
> +Users can use Singularity to support many applications, such as Python, R, C/Fortran packages, and many GUI software. In particular, container is polular in supporting Python pakcages for the artific
container is -> containers are
polular -> popular
convinent -> convenient
enviroenment -> environment

2024-08-23 18:55 UTC, lmilechin commented on docs/software/apptainer.md
> +In this docuemnt, we will focuse on how to use Singularity on ORCD clusters. First, many applications are well-supported in existing Docker images. Search for an image on the internet, in which your
docuemnt -> document
focuse -> focus

2024-08-23 18:55 UTC, lmilechin commented on docs/software/apptainer.md
> +     Log in a Rocky 8 head node,
Log in a -> Log in to a

2024-08-23 18:55 UTC, lmilechin commented on docs/software/apptainer.md
> +     Log in a the head node,
Log in a the -> Log in to the

2024-08-23 18:55 UTC, lmilechin commented on docs/software/apptainer.md
> +     #SBATCH -p sched_mit_psfc_gpu_r8     # a partition with Rocky 8 nodes
We should avoid using PI or OU resources in documentation examples. If this example only works on Rocky 8 we can put sched_mit_orcd here for now as the partition. Better would be to use a Centos 7 example until we have public Rocky 8 nodes

2024-08-23 18:55 UTC, lmilechin commented on docs/software/apptainer.md
> +In the previous section, it is assumed that all needed packages have been installed in the image. If some needed packages do not exist in the image, users need to build a new image.
We may want to add a note here that says building containers is currently not supported on Engaging.

2024-08-23 18:55 UTC, lmilechin commented on docs/software/apptainer.md
> +??? note
Remove this note, if we add the note above that building containers on Engaging is not supported currently we don't need this note here.

2024-08-23 18:55 UTC, lmilechin commented on mkdocs.yml
> +#    - Singularity/Apptainer:
Uncomment and add the path to this file

2025-01-16 17:04 UTC, merged