WIP: Adding Snippets
mit-orcd/orcd-docs-edit pull request #57
Opened 2024-05-29 14:58 UTC by kcnakamu

2024-05-29 18:02 UTC, kcnakamu commented
https://mit-orcd.github.io/orcd-docs-previews/PR/PR57

2024-07-31 15:07 UTC, lmilechin requested changes
A few things to fix, once these are done we can probably merge!

2024-07-31 15:07 UTC, lmilechin commented on docs/recipes/snippets-setup/mpi4py/OpenMind.sh
If these have been added to the examples repo then we can delete these from this one.

2024-08-23 20:34 UTC, lmilechin approved these changes
Looks good!

2024-08-23 20:34 UTC, merged